services:
  MachinesAPI:
    image: ${DOCKER_REGISTRY-}machinesapi
    build:
      context: .
      dockerfile: "Machines API/Domain.Tests/Dockerfile"
    networks:
      - machines_data_analyzing_network
    ports:
      - 6969:8080
    stdin_open: true
    tty: true

  MachinesDataCollectorService:
    image: ${DOCKER_REGISTRY-}machinesdatacollectorservice
    build:
      context: .
      dockerfile: "Machines data collector service/Domain.Tests/Dockerfile"
    networks:
      - machines_data_analyzing_network
    stdin_open: true
    tty: true

  DataBaseDataSaverService:
    image: ${DOCKER_REGISTRY-}databasesaverservice
    build:
      context: .
      dockerfile: "DataBase data saver service/Domain.Tests/Dockerfile"
    networks:
      - machines_data_analyzing_network
    stdin_open: true
    tty: true

  DataAnalyzingWebApp:
    image: ${DOCKER_REGISTRY-}dataanalyzingwebapp
    build:
      context: .
      dockerfile: "Data analyzing web app/Domain.Tests/Dockerfile"
    networks:
      - machines_data_analyzing_network
    ports:
      - 6970:8080
    environment:
      APIHostName: "MachinesAPI:8080"
    stdin_open: true
    tty: true

networks:
  machines_data_analyzing_network:
    external: true
    name: machines_data_analyzing_network 